
services:
  openhands:
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    image: openhands:latest
    container_name: openhands-app-${DATE:-}
    environment:
      environment:
  - SANDBOX_RUNTIME_CONTAINER_IMAGE=${SANDBOX_RUNTIME_CONTAINER_IMAGE:-docker.all-hands.dev/all-hands-ai/runtime:0.54-nikolaik}
  #- SANDBOX_USER_ID=${SANDBOX_USER_ID:-1234} 
  - WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE:-$PWD/workspace}
  
  # Add these Pollinations AI settings:
     - LLM_MODEL=qwen-coder
     - LLM_BASE_URL=https://text.pollinations.ai/openai
     - LLM_API_KEY=""
     - LLM_PROVIDER=openai
     - LLM_NATIVE_TOOL_CALLING=true
     - LLM_INPUT_COST_PER_TOKEN=0.0
     - LLM_OUTPUT_COST_PER_TOKEN=0.0
     - OPENHANDS_FREE_MODE=true
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=${SANDBOX_RUNTIME_CONTAINER_IMAGE:-docker.all-hands.dev/all-hands-ai/runtime:0.54-nikolaik}
      #- SANDBOX_USER_ID=${SANDBOX_USER_ID:-1234} # enable this only if you want a specific non-root sandbox user but you will have to manually adjust permissions of ~/.openhands for this user
      - WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE:-$PWD/workspace}
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands:/.openhands
      - ${WORKSPACE_BASE:-$PWD/workspace}:/opt/workspace_base
    pull_policy: build
    stdin_open: true
    tty: true
