services:
  openhands:
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    image: openhands:latest
    container_name: openhands-app
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.54-nikolaik
      - WORKSPACE_MOUNT_PATH=/opt/workspace_base
      # Pollinations AI Configuration
      - LLM_MODEL=deepseek-reasoning
      - LLM_BASE_URL=https://text.pollinations.ai/openai
      - LLM_API_KEY=""
      - LLM_PROVIDER=openai
      - LLM_NATIVE_TOOL_CALLING=true
      - LLM_INPUT_COST_PER_TOKEN=0.0
      - LLM_OUTPUT_COST_PER_TOKEN=0.0
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands:/.openhands
      - ./workspace:/opt/workspace_base
    stdin_open: true
    tty: true
